[package]
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]
name = "curses-game-wrapper"
version = "0.0.1"

[dependencies]
ascii = "0.8.6"
bitflags = "1.0.1"
slog = "2.0.12"
sloggers = "0.2.2"
vte = "0.3.2"
